### ISSUE TITLE
IE conditional comments

### ISSUE THREAD

**Issue by dalf** [asciimoo/morty#12]
CSS and HTML in IE conditional comments are not proxified.
They can be harmful if IE is used.

Should morty remove them or parse the content ?

**Comment by dalf** [comment]
And there are HTC behaviors in CSS : 
* https://css-tricks.com/forums/topic/what-is-a-htc-file/
* https://en.wikipedia.org/wiki/HTML_Components

**Comment by asciimoo** [comment]
It would be good to parse them  and sanitize if the user-agent is IE or skip if it isn't IE.
