### ISSUE TITLE
Content-Type:application/xhtml+xml and closing elements

### ISSUE THREAD

**Issue by dalf** [asciimoo/morty#17]
When the content type is application/xhtml+xml, the document should be XML compliant not SGML / HTML. The browsers (FF, Chrome at least) displays error instead of the page.

Example : http://eu.battle.net/forums/fr/wow/

The browser see nested elements here :
```html
<link rel="shortcut icon" type="image/x-icon" href="./?mortyurl=http%3A%2F%2Feu.battle.net%2Fforums%2Fstatic%2Fimages%2Ficons%2Fwow-favicon.ico">
<link rel="stylesheet" type="text/css" media="all" href="./?mortyurl=http%3A%2F%2Feu.battle.net%2Fforums%2Fstatic%2Fcss%2Fnav-client%2Fnav-client.css%3Fv%3D84">
```

It should be (with a ```/``` at the end) : 
```html
<link rel="shortcut icon" type="image/x-icon" href="..." />
<link rel="stylesheet" type="text/css" media="all" href="..." />
```

More over, the namespace of the ```html``` element is removed by morty. Original is : 
```html
<html xmlns="http://www.w3.org/1999/xhtml">
```
----
A dirty way is to fix the problem, is to replace ```Content-Type:application/xhtml+xml``` with ```Content-Type:text/html```, but the rendering may be different.

**Comment by asciimoo** [comment]
As a first solution content-type replacement is ok imho
