### ISSUE TITLE
Content-Disposition header

### ISSUE THREAD

**Issue by dalf** [asciimoo/morty#21]
For mimetype which are not html, image nor css, should the Content-Disposition header should be forwarded or set ?

Suggestion for URL https://f-droid.org/FDroid.apk : 
```
Content-Disposition: inline; filename="FDroid.apk"
```

FDroid.apk would be the last part of the URL if the header is not already set.

Opposite direction : cancel the download.

**Comment by asciimoo** [comment]
It would be good to forward this header, agree
