### ISSUE TITLE
proxy of github.com : some css resources can't be loaded

### ISSUE THREAD

**Issue by dalf** [asciimoo/morty#3]
The loading of the following URLs doesn't work :
- https://assets-cdn.github.com/assets/frameworks-7a356da712cd13c4e4cfbdc04cf886bb391f84a7e92f9f7b3abf2b1034fea6e9.css
- https://assets-cdn.github.com/assets/github-ab5f174418be0dd006b8768666c1f242afdca1e454279d19ad4e54b00ca5495d.css

**Comment by asciimoo** [comment]
both works for me on my local morty

**Comment by dalf** [comment]
working now. I close.
