### ISSUE TITLE
Installing morty for Searx

### ISSUE THREAD

**Issue by mrtargaryen** [asciimoo/morty#50]
I have installed the Docker app on my iMac 2015 10.12.6.

How do I install Morty on macOS?

I have installed Searx via Kitematic and can use Searx on my localhost in my Firefox Browser.

However, I am not sure how to install Morty https://github.com/asciimoo/morty

When I type $ go get github.com/asciimoo/morty (as instructed) it returns the following: -bash: go: command not found

Does anybody know what I am doing wrong?

Is there an easy guide to installing and using Morty with Searx?

Any help or suggestion is really appreciated.

Thanks

**Comment by RaspyVotan** [comment]
You may have Go not installed on your machine - depending on your system, try:
sudo apt-get install golang
As soon as Go is installed, you will be able to download as described above (In some distributions you may have an issue with $GOPATH, have a look with google and you will see how to solve.
