### ISSUE TITLE
Can we have a release?

### ISSUE THREAD

**Issue by josch** [asciimoo/morty#53]
Hi,

I'm the Debian maintainer of the searx package. Since morty works well with searx, I'd love to also package it and make it such that it works well in combination with searx.

But to package it, it would make things much easier and more convenient, if morty could make a release.

Would you consider making one?

Thanks!

cheers, josch

**Comment by asciimoo** [comment]
@josch first of all, thank you for packaging morty. Sure, we can have releases, this is a good reason for creating releases. I'm adding an initial `0.1.0` release.

**Comment by asciimoo** [comment]
@josch i've created an initial release with the current codebase: https://github.com/asciimoo/morty/releases/tag/v0.1.0

**Comment by josch** [comment]
Thank you!! :)
