### ISSUE TITLE
Morty not doing anything

### ISSUE THREAD

**Issue by greentea47** [asciimoo/morty#72]
I have searx installed as a local instance and it is running fine, and also have installed morty and adjusted the /etc/searx/settings.yaml  accordingly.

Searching works but I cannot tell if morty is doing anything. There's no output in the terminal morty is running in and the searx output doesn't show anything morty related.  Also, if I attach strace to the morty PID, morty remains idle and does nothing when I search.

Is there some logging I'm missing somewhere?  What should I be seeing if morty is working correctly?

**Comment by madmath03** [comment]
Hi @greentea47 ,

I'm testing Morty with Searx and from what I see, if you have configured it correctly, you should see a "_ proxied_" link in your tests results if Morty is properly setup:
![image](https://user-images.githubusercontent.com/6967675/66787615-a33aba80-eee4-11e9-82f4-cdecceaa19e6.png)


When you click on it, you should see a sanitized version of the page with a box on the side explaining this:
![image](https://user-images.githubusercontent.com/6967675/66787664-d11fff00-eee4-11e9-8050-3a234cc01163.png)

Hope that can help you.

**Comment by return42** [comment]
can we close this issue?
