### ISSUE TITLE
Error: remote error: tls: internal error

### ISSUE THREAD

**Issue by josch** [asciimoo/morty#83]
Hi,

when trying to open https://www.bild.de via morty, I'm getting "remote error: tls: internal error" on the result page as well as in the log. I tried setting `DEBUG=true` but didn't get any more output than that.

Could the debug output maybe be enhanced so that one can figure out what the problem is?

Thanks!

cheers, josch

**Comment by dalf** [comment]
Commit bb63e524d913affff731875dfd1d92f6b6bbc5b5 upgrades the dependencies.

There is no more TLS error, unfortunately the website requires Javascript, which can't be fixed.
