### ISSUE TITLE
Some CLI flags not being parsed properly

### ISSUE THREAD

**Issue by maxweisspoker** [asciimoo/morty#96]
Something in commit a549f668b4cf8cf79320e252cd05f6a0f02191b8 screwed up the parsing of command line flags. In particular, the "listen" CLI flag does not get read and reverts to the default localhost address (unless the env var is set).

More info in my comment [here](https://github.com/asciimoo/morty/issues/95)

**Comment by Zaczero** [comment]
That's still a thing 🤒.
The only way to set parameters is to use system environment variables.

*bump*
