### ISSUE TITLE
[enhancement] Support for HTTP proxy

### ISSUE THREAD

**Issue by aureq** [asciimoo/morty#99]
Hi @asciimoo 

Thank you for creating Morty. I noticed Morty supports a socks5 proxy using `-socks5` option. I`m wondering if there's any plans to support regular [HTTP proxies](https://pkg.go.dev/github.com/valyala/fasthttp/fasthttpproxy#FasthttpHTTPDialer) like Squid cache? And if not, are you ok if I prepare and submit a PR?

Thank you

**Comment by asciimoo** [comment]
Thanks for #100.
